# Generated by Django 4.1.2 on 2022-11-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_contact_down_delete_contacts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Down",
            new_name="Down_images",
        ),
    ]
