# Generated by Django 4.1.2 on 2022-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_rename_down_down_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=50, null=True)),
                ("name2", models.CharField(max_length=50, null=True)),
                ("name3", models.CharField(max_length=50, null=True)),
                ("insta", models.CharField(max_length=40, null=True)),
                ("phone_number1", models.CharField(max_length=15)),
                ("phone_number2", models.CharField(max_length=15)),
                ("phone_number3", models.CharField(max_length=15)),
                ("adres", models.CharField(max_length=100)),
                ("image_mem", models.ImageField(upload_to="")),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
