# Generated by Django 4.1.2 on 2022-11-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_contacts_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Down_images',
        ),
    ]
