# Generated by Django 4.1.2 on 2022-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_about_us_contact_delete_about_delete_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('image_down1', models.ImageField(upload_to='')),
                ('image_down2', models.ImageField(upload_to='')),
                ('image_down3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='')),
                ('text_welcome', models.TextField()),
                ('text_repair', models.TextField()),
                ('text_services', models.TextField()),
                ('client1', models.CharField(max_length=100)),
                ('client1_info', models.TextField()),
                ('client2', models.CharField(max_length=100)),
                ('client2_info', models.TextField()),
                ('client3', models.CharField(max_length=100)),
                ('client3_info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About_us',
        ),
    ]
