# Generated by Django 4.1.2 on 2022-11-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_main_delete_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Main_m',
        ),
    ]
