# Generated by Django 4.1.2 on 2022-11-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_form_rename_main_m_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
