# Generated by Django 4.1.2 on 2022-11-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_send"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Send",
        ),
    ]
