# Generated by Django 4.1.2 on 2022-11-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
