# Generated by Django 4.1.2 on 2022-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_manclothing_delete_send_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_image", models.ImageField(upload_to="")),
                ("text_welcome", models.TextField()),
                ("text_repair", models.TextField()),
                ("text_services", models.TextField()),
                ("client1", models.CharField(max_length=100)),
                ("client1_info", models.TextField()),
                ("client2", models.CharField(max_length=100)),
                ("client2_info", models.TextField()),
                ("client3", models.CharField(max_length=100)),
                ("client3_info", models.TextField()),
                ("repair_image", models.ImageField(upload_to="")),
                ("service_image", models.ImageField(upload_to="")),
                ("image_down1", models.ImageField(upload_to="")),
                ("image_down2", models.ImageField(upload_to="")),
                ("image_down3", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair1", models.CharField(max_length=100)),
                ("repair2", models.CharField(max_length=100)),
                ("repair3", models.CharField(max_length=100)),
                ("repair4", models.CharField(max_length=100)),
                ("repair5", models.CharField(max_length=100)),
                ("repair6", models.CharField(max_length=100)),
                ("repair7", models.CharField(max_length=100)),
                ("repair8", models.CharField(max_length=100)),
                ("repair9", models.CharField(max_length=100)),
                ("price1", models.CharField(max_length=20)),
                ("price2", models.CharField(max_length=20)),
                ("price3", models.CharField(max_length=20)),
                ("price4", models.CharField(max_length=20)),
                ("price5", models.CharField(max_length=20)),
                ("price6", models.CharField(max_length=20)),
                ("price7", models.CharField(max_length=20)),
                ("price8", models.CharField(max_length=20)),
                ("price9", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=13)),
                (
                    "broken",
                    models.CharField(
                        choices=[
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                            (
                                models.CharField(max_length=100),
                                models.CharField(max_length=100),
                            ),
                        ],
                        max_length=60,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Main",
        ),
        migrations.DeleteModel(
            name="ManClothing",
        ),
    ]
