# Generated by Django 4.1.2 on 2022-11-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_home_service_delete_main_delete_manclothing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair1", models.CharField(max_length=100)),
                ("repair2", models.CharField(max_length=100)),
                ("repair3", models.CharField(max_length=100)),
                ("repair4", models.CharField(max_length=100)),
                ("repair5", models.CharField(max_length=100)),
                ("repair6", models.CharField(max_length=100)),
                ("repair7", models.CharField(max_length=100)),
                ("repair8", models.CharField(max_length=100)),
                ("repair9", models.CharField(max_length=100)),
                ("price1", models.CharField(max_length=20)),
                ("price2", models.CharField(max_length=20)),
                ("price3", models.CharField(max_length=20)),
                ("price4", models.CharField(max_length=20)),
                ("price5", models.CharField(max_length=20)),
                ("price6", models.CharField(max_length=20)),
                ("price7", models.CharField(max_length=20)),
                ("price8", models.CharField(max_length=20)),
                ("price9", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Service_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=13)),
                (
                    "broken",
                    models.CharField(
                        choices=[
                            ("TV", "TV"),
                            ("Refrigerator", "Refrigerator"),
                            ("Microwave ovens", "Microwave ovens"),
                            ("Washing machine", "Washing machine"),
                            ("Electric cooker", "Electric cooker"),
                            ("Gas cooker", "Gas cooker"),
                            ("Vacuum cleaners", "Vacuum cleaners"),
                            ("Irons", "Irons"),
                            ("Electric kettle", "Electric kettle"),
                        ],
                        max_length=60,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
