# Generated by Django 4.1.2 on 2022-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_service_content_image1_service_content_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_content',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
