# Generated by Django 4.1.2 on 2022-11-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_service_content_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='text_call',
            field=models.TextField(null=True),
        ),
    ]
