# Generated by Django 4.1.2 on 2022-11-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_home_text_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_form',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
