# Generated by Django 4.1.2 on 2022-11-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_form_delete_service_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
    ]
