# Generated by Django 4.1.2 on 2022-11-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0037_form_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="created_date",
        ),
        migrations.AddField(
            model_name="form",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
