# Generated by Django 4.1.2 on 2022-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0041_delete_service_table_service_content_image_down1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guides",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
