# Generated by Django 4.1.2 on 2022-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_contact_link_address_contact_link_inst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
