# Generated by Django 4.1.2 on 2022-12-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0045_alter_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
    ]
